# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\JetBrains\CLion 2022.3.2\bin\cmake\win\x64\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\JetBrains\CLion 2022.3.2\bin\cmake\win\x64\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\src\TicTacToe

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\src\TicTacToe

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	"C:\Program Files\JetBrains\CLion 2022.3.2\bin\cmake\win\x64\bin\cmake.exe" -E echo "No interactive CMake dialog available."
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\JetBrains\CLion 2022.3.2\bin\cmake\win\x64\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\src\TicTacToe\CMakeFiles C:\src\TicTacToe\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\src\TicTacToe\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named TicTacToe

# Build rule for target.
TicTacToe: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 TicTacToe
.PHONY : TicTacToe

# fast build rule for target.
TicTacToe/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TicTacToe.dir\build.make CMakeFiles/TicTacToe.dir/build
.PHONY : TicTacToe/fast

Console/Console.obj: Console/Console.cpp.obj
.PHONY : Console/Console.obj

# target to build an object file
Console/Console.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TicTacToe.dir\build.make CMakeFiles/TicTacToe.dir/Console/Console.cpp.obj
.PHONY : Console/Console.cpp.obj

Console/Console.i: Console/Console.cpp.i
.PHONY : Console/Console.i

# target to preprocess a source file
Console/Console.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TicTacToe.dir\build.make CMakeFiles/TicTacToe.dir/Console/Console.cpp.i
.PHONY : Console/Console.cpp.i

Console/Console.s: Console/Console.cpp.s
.PHONY : Console/Console.s

# target to generate assembly for a file
Console/Console.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TicTacToe.dir\build.make CMakeFiles/TicTacToe.dir/Console/Console.cpp.s
.PHONY : Console/Console.cpp.s

MiniMax/MiniMax.obj: MiniMax/MiniMax.cpp.obj
.PHONY : MiniMax/MiniMax.obj

# target to build an object file
MiniMax/MiniMax.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TicTacToe.dir\build.make CMakeFiles/TicTacToe.dir/MiniMax/MiniMax.cpp.obj
.PHONY : MiniMax/MiniMax.cpp.obj

MiniMax/MiniMax.i: MiniMax/MiniMax.cpp.i
.PHONY : MiniMax/MiniMax.i

# target to preprocess a source file
MiniMax/MiniMax.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TicTacToe.dir\build.make CMakeFiles/TicTacToe.dir/MiniMax/MiniMax.cpp.i
.PHONY : MiniMax/MiniMax.cpp.i

MiniMax/MiniMax.s: MiniMax/MiniMax.cpp.s
.PHONY : MiniMax/MiniMax.s

# target to generate assembly for a file
MiniMax/MiniMax.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TicTacToe.dir\build.make CMakeFiles/TicTacToe.dir/MiniMax/MiniMax.cpp.s
.PHONY : MiniMax/MiniMax.cpp.s

Playground/Playground.obj: Playground/Playground.cpp.obj
.PHONY : Playground/Playground.obj

# target to build an object file
Playground/Playground.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TicTacToe.dir\build.make CMakeFiles/TicTacToe.dir/Playground/Playground.cpp.obj
.PHONY : Playground/Playground.cpp.obj

Playground/Playground.i: Playground/Playground.cpp.i
.PHONY : Playground/Playground.i

# target to preprocess a source file
Playground/Playground.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TicTacToe.dir\build.make CMakeFiles/TicTacToe.dir/Playground/Playground.cpp.i
.PHONY : Playground/Playground.cpp.i

Playground/Playground.s: Playground/Playground.cpp.s
.PHONY : Playground/Playground.s

# target to generate assembly for a file
Playground/Playground.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TicTacToe.dir\build.make CMakeFiles/TicTacToe.dir/Playground/Playground.cpp.s
.PHONY : Playground/Playground.cpp.s

TicTacToe/TicTacToe.obj: TicTacToe/TicTacToe.cpp.obj
.PHONY : TicTacToe/TicTacToe.obj

# target to build an object file
TicTacToe/TicTacToe.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TicTacToe.dir\build.make CMakeFiles/TicTacToe.dir/TicTacToe/TicTacToe.cpp.obj
.PHONY : TicTacToe/TicTacToe.cpp.obj

TicTacToe/TicTacToe.i: TicTacToe/TicTacToe.cpp.i
.PHONY : TicTacToe/TicTacToe.i

# target to preprocess a source file
TicTacToe/TicTacToe.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TicTacToe.dir\build.make CMakeFiles/TicTacToe.dir/TicTacToe/TicTacToe.cpp.i
.PHONY : TicTacToe/TicTacToe.cpp.i

TicTacToe/TicTacToe.s: TicTacToe/TicTacToe.cpp.s
.PHONY : TicTacToe/TicTacToe.s

# target to generate assembly for a file
TicTacToe/TicTacToe.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TicTacToe.dir\build.make CMakeFiles/TicTacToe.dir/TicTacToe/TicTacToe.cpp.s
.PHONY : TicTacToe/TicTacToe.cpp.s

Util/Util.obj: Util/Util.cpp.obj
.PHONY : Util/Util.obj

# target to build an object file
Util/Util.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TicTacToe.dir\build.make CMakeFiles/TicTacToe.dir/Util/Util.cpp.obj
.PHONY : Util/Util.cpp.obj

Util/Util.i: Util/Util.cpp.i
.PHONY : Util/Util.i

# target to preprocess a source file
Util/Util.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TicTacToe.dir\build.make CMakeFiles/TicTacToe.dir/Util/Util.cpp.i
.PHONY : Util/Util.cpp.i

Util/Util.s: Util/Util.cpp.s
.PHONY : Util/Util.s

# target to generate assembly for a file
Util/Util.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TicTacToe.dir\build.make CMakeFiles/TicTacToe.dir/Util/Util.cpp.s
.PHONY : Util/Util.cpp.s

main.obj: main.cpp.obj
.PHONY : main.obj

# target to build an object file
main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TicTacToe.dir\build.make CMakeFiles/TicTacToe.dir/main.cpp.obj
.PHONY : main.cpp.obj

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TicTacToe.dir\build.make CMakeFiles/TicTacToe.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TicTacToe.dir\build.make CMakeFiles/TicTacToe.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... TicTacToe
	@echo ... Console/Console.obj
	@echo ... Console/Console.i
	@echo ... Console/Console.s
	@echo ... MiniMax/MiniMax.obj
	@echo ... MiniMax/MiniMax.i
	@echo ... MiniMax/MiniMax.s
	@echo ... Playground/Playground.obj
	@echo ... Playground/Playground.i
	@echo ... Playground/Playground.s
	@echo ... TicTacToe/TicTacToe.obj
	@echo ... TicTacToe/TicTacToe.i
	@echo ... TicTacToe/TicTacToe.s
	@echo ... Util/Util.obj
	@echo ... Util/Util.i
	@echo ... Util/Util.s
	@echo ... main.obj
	@echo ... main.i
	@echo ... main.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

